# Generated by Django 4.0.6 on 2022-07-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_transport_destination_transport_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('check_in_date', models.DateTimeField(null=True)),
                ('check_out_date', models.DateTimeField(null=True)),
                ('address_link', models.URLField(blank=True)),
                ('reservation_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address_link', models.URLField(null=True)),
                ('additional_resources', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='accommodations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.accommodation'),
        ),
        migrations.AddField(
            model_name='destination',
            name='sites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.site'),
        ),
    ]
