# Generated by Django 4.0.6 on 2022-08-06 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_accommodation_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(blank=True, null=True, to='trips.destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.transport'),
        ),
    ]
