# Generated by Django 4.0.6 on 2022-08-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_trip_destinations_alter_trip_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='arrive_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='depart_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='arrive',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='depart',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
