# Generated by Django 4.0.6 on 2022-08-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_rename_destination_accommodation_destination_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_transport', models.BooleanField(default=False)),
                ('depart_time', models.DateTimeField(blank=True)),
                ('arrive_time', models.DateTimeField(blank=True)),
                ('start_location', models.CharField(blank=True, max_length=120)),
                ('end_location', models.CharField(blank=True, max_length=120)),
                ('type', models.CharField(choices=[('DEFAULT', ''), ('AIR', 'Airplane'), ('TRAIN', 'Train'), ('BOAT', 'Boat'), ('BUS', 'Bus'), ('CAR', 'Car')], default='DEFAULT', max_length=25)),
                ('info_link', models.URLField(blank=True)),
                ('destination_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='trips.destination')),
            ],
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='destination_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='trips.destination'),
        ),
        migrations.AlterField(
            model_name='site',
            name='destination_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='trips.destination'),
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
