# Generated by Django 4.0.6 on 2022-08-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_transportation_alter_accommodation_destination_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportation',
            options={'verbose_name_plural': 'Transportation'},
        ),
    ]
