# Generated by Django 4.0.6 on 2022-07-29 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_end_date_alter_trip_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.DateTimeField(null=True)),
                ('arrive', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField()),
                ('info_link', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.transport'),
        ),
    ]
