# Generated by Django 4.0.6 on 2022-07-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='destination',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='origin',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
