# Generated by Django 4.0.6 on 2022-07-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_accommodation_site_destination_accommodations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='accommodations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.accommodation'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='sites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.site'),
        ),
    ]
