# Generated by Django 4.0.6 on 2022-08-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_alter_destination_arrive_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='arrive',
            new_name='arrive_time',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='depart',
            new_name='depart_time',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='accommodations',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='transport',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.destination'),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
        migrations.AddField(
            model_name='site',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.destination'),
        ),
        migrations.AddField(
            model_name='transport',
            name='end_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transport',
            name='initial_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transport',
            name='start_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='transport',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.destination'),
        ),
    ]
