# Generated by Django 4.0.6 on 2022-08-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_rename_arrive_transport_arrive_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='destination',
            new_name='destination_id',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='destination',
            new_name='destination_id',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='destination',
            new_name='destination_id',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='trip',
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='trips.trip'),
        ),
    ]
