# Generated by Django 4.0.6 on 2022-08-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_rename_destination_id_accommodation_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
